DwarfGameMVC/Models/NPCListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DwarfGameMVC.Models
{
    public class NPCListViewModel
    {
        public List<NPCModel> NPCs { get; set; }
    }
}

DwarfGameMVC/Models/NPCModel.cs
using DwarfGame.DAL.Model;
using DwarfGame.Shared.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DwarfGameMVC.Models
{
    public class NPCModel
    {
        public Guid Id { get; set; }
        [Required (ErrorMessage ="Please enter a name")] public string Name { get; set; }
        [Required (ErrorMessage = "Please pick a race")] public PlayerRace PlayerRace { get; set; }
        [Required (ErrorMessage = "Please enter a goldvalue")] [Range (50, 200, ErrorMessage = "min 50, max 200")] public int StartGold { get; set; }
        [Required (ErrorMessage = "Please enter a bluffchance")] [Range (0, 100, ErrorMessage = "min 0, max 100")]public int BluffChance { get; set; }

        public static NPCModel FromDatabaseModel(NPC npc)
        {
            return new NPCModel
            {
                Id = npc.Id,
                Name = npc.Name,
                PlayerRace = npc.PlayerRace,
                StartGold = npc.StartGold,
                BluffChance = npc.BluffChance
             
            };
        }

        public static NPC ToDatabaseModel(NPCModel model)
        {
            return new NPC
            {
                Name = model.Name,
                PlayerRace = model.PlayerRace,
                StartGold = model.StartGold,
                BluffChance = model.BluffChance
            };
        }
    }
}

DwarfGameMVC/Models/PlayerListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DwarfGameMVC.Models
{
    public class PlayerListViewModel
    {
        public List<PlayerModel> Players { get; set; }
    }
}

DwarfGameMVC/Models/PlayerModel.cs
using DwarfGame.DAL.Model;
using DwarfGame.Shared.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DwarfGameMVC.Models
{
    public class PlayerModel
    {
        [Required] public string Name { get; set; }
        [Required] public PlayerRace PlayerRace { get; set; }
        [Required] public PlayerClass PlayerClass { get; set; }

        public static PlayerModel FromDatabaseModel(Player player)
        {
            return new PlayerModel
            {
                Name = player.Name,
                PlayerClass = player.PlayerClass,
                PlayerRace = player.PlayerRace
            };
        }

        public static Player ToDatabaseModel(PlayerModel player)
        {
            return new Player
            {
                Name = player.Name,
                PlayerRace = player.PlayerRace,
                PlayerClass = player.PlayerClass

            };
        }
    }
}

DwarfGameMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DwarfGameMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.  Commit example";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Rules()
        {
            ViewBag.Message = "The rules to the game.";

            return View();
        }
    }
}

DwarfGameMVC/Controllers/NPCController.cs
using DwarfGame.DAL;
using DwarfGameMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DwarfGameMVC.Controllers
{
    public class NPCController : Controller
    {
        NPCRepository npcRepository = new NPCRepository();

        // GET: NPC

        public ActionResult Index()
        {
            var model = new NPCListViewModel();
            var NPCs = npcRepository.GetAll();
            model.NPCs = NPCs.Select(p => NPCModel.FromDatabaseModel(p)).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NPCModel model)
        {
            if (ModelState.IsValid)
            {

                npcRepository.Add(NPCModel.ToDatabaseModel(model));

                return RedirectToAction("Index");

            }

            return View(model);

        }

        public ActionResult Edit(Guid id)
        {
            var model = NPCModel.FromDatabaseModel(npcRepository.GetNPC(id));
            return View(model);

        }
       
        public ActionResult Delete(Guid id)
        {
            npcRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

DwarfGameMVC/Controllers/PlayerController.cs
using DwarfGame.DAL;
using DwarfGameMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DwarfGameMVC.Controllers
{
    public class PlayerController : Controller
    {
        PlayerRepository playerRepository = new PlayerRepository();

        // GET: Player
        public ActionResult Index()
        {
            var model = new PlayerListViewModel();
            var players = playerRepository.GetAll();
            model.Players = players.Select(p => PlayerModel.FromDatabaseModel(p)).ToList();
            return View(model);
        }

       

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PlayerModel model)
        {
            if (ModelState.IsValid)
            {

                playerRepository.Add(PlayerModel.ToDatabaseModel(model));

                return RedirectToAction("Index");

            }

            return View(model);

        }
    }

}

DwarfGameMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<div>
    Welcome to Vozzerts dwarven dicegame! After a glorious console version and a slightly less glorious win-forms version, it's time to get it online in a MVC-application!<br />
    I created this page to sharpen my C#, MVC, HTML, CSS skills. 
</div>

DwarfGameMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>



<address>
    <strong>feedback and/or questions?:</strong>   <a href="mailto:fernandvos@yahoo.co.uk">fernandvos@yahoo.co.uk</a><br />
    
</address>

DwarfGameMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<img src="https://s-media-cache-ak0.pinimg.com/236x/ea/99/5c/ea995c08a6399876a62ed67ba4b9b357.jpg" />

DwarfGameMVC/Views/Home/Rules.cshtml
@{
    ViewBag.Title = "Rules";
}

<h2>Rules</h2>

<div class="jumbotron">Welcome to the inn!<br />
    here we play a dicegame, called 3D20. <br />
    You and your opponent both roll 3 D20. 
    The player who's turn it is, chooses one, his bet-die. Both players put an amount of gold in the stash equal to the shown die. 
    If the other player wants, he can chicken out and loose this round (and his gold on the stash!)
    Now the other player also shows a bet-die and again, both players again put that amount of gold in the stash.
    Next both players show pick a game-die and show it. You get a slight bonus on your game-die derived from your bet-die.
    If your bet-die was 5 till 15, you get a +1 bonus on your game-die. If your bet-die was 16 or higher, you get a +2 bonus. 
    Highest game-die (including bonus) wins the stash! If their is a tie, the gold stays in the stash and the next round will be a whole lot more interesting!

    </div>

DwarfGameMVC/Views/NPC/Create.cshtml
@model DwarfGameMVC.Models.NPCModel

@{
    ViewBag.Title = "Create";
}

<h2>Creating a new NPC</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Please fill in the details</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
       
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerRace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(
                x => x.PlayerRace,
                "Select My Type",
                new { @class = "form-control" })

            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.StartGold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartGold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartGold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BluffChance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BluffChance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BluffChance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
 </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DwarfGameMVC/Views/NPC/Edit.cshtml
@model DwarfGameMVC.Models.NPCModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NPCModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.PlayerRace, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(
              x => x.PlayerRace,
              "Select My Type",
              new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartGold, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartGold, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartGold, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BluffChance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BluffChance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BluffChance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DwarfGameMVC/Views/NPC/Index.cshtml
@model DwarfGameMVC.Models.NPCListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Starting Gold</th>
        <th>Bluff Chance</th>
    </tr>

    @foreach (var item in Model.NPCs)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.PlayerRace
            </td>
            <td>
                @item.StartGold
            </td>
            <td>
                @item.BluffChance

            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) 
                @Html.ActionLink("Details", "Details", new { id = item.Id }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

DwarfGameMVC/Views/Player/Create.cshtml
@model DwarfGameMVC.Models.PlayerModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new player</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Fill in tha damnes f0rm!</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PlayerRace, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(
                      x => x.PlayerRace,
                      "Pick one....",
                      new { @class = "form-control" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PlayerClass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(
                 x => x.PlayerClass,
                 "Pick one....",
                 new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DwarfGameMVC/Views/Player/Index.cshtml
@model DwarfGameMVC.Models.PlayerListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Class</th>
        <th>Race</th>
    </tr>

@foreach (var item in Model.Players) {
    <tr>
        <td>
            @item.Name
        </td>
        <td>
            @item.PlayerClass
        </td>
        <td>
            @item.PlayerRace
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

DwarfGameMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DwarfGame 3.0 MVC-style</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href='@Url.Action("Index", "Home")'>
                    <img src='@Url.Content("https://s-media-cache-ak0.pinimg.com/236x/ea/99/5c/ea995c08a6399876a62ed67ba4b9b357.jpg")' height="50" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rules", "Rules", "Home")</li>
                    <li>@Html.ActionLink("Players", "Index", "Player")</li>
                    <li>@Html.ActionLink("NPC", "Index", "NPC")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vozzert</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>